/* SEMIIRA pocket life. Parent UI/Three.js; pure state and games in separate modules. */
(() => {'use strict';
const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,L=TamaLife;
let pet=L.advance(),state={action:pet.sleeping?'sleep':'idle',until:0,started:0,selected:0,menu:'home',food:'cookie'},game=null,roundId='',rewarded=false,gameStart=0,wardrobe=null,pendingImport=null;
const options=[{id:'food',label:'Покормить',icon:'food',hint:'Три блюда · бесплатно'},{id:'game',label:'Поиграть',icon:'game',hint:'Змейка, звёзды, память'},{id:'bath',label:'Искупать',icon:'bath',hint:'+35 чистоты'},{id:'sleep',label:'Уложить спать',icon:'sleep',hint:'Отдых по реальному времени'},{id:'bow',label:'Поправить бант',icon:'bow',hint:'Расправить и выровнять'}];
function downloadFullSave(name='semiira-full-save.json'){lifeTick();const url=URL.createObjectURL(new Blob([L.exportSave()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const lifeUI=createLifecycleUI({state,getPet:()=>pet,refresh,home,act,message,download:downloadFullSave,error:code=>errors[code]||'Не получилось. Проверь состояние.'});
const foods=[{id:'cookie',label:'Печенька с бантом',hint:'+12 сытости · +5 бодрости · +4 радости · −2 чистоты'},{id:'soup',label:'Тёплый суп',hint:'+25 сытости · +12 бодрости'},{id:'berry',label:'Ягодки',hint:'+8 сытости · +4 бодрости'}];
const gameChoices=[{id:'snake',label:'Змейка',hint:'Собери 8 ягод · не врежься'},{id:'stars',label:'Звездопад',hint:'Поймай 5 из 8 звёзд'},{id:'memory',label:'Парочки',hint:'Найди 6 одинаковых пар'}];
const needInfo={hunger:['Сытость','#e6a3c1','Еда наполняет эту полоску'],joy:['Радость','#d5addd','Игры и забота поднимают настроение'],energy:['Бодрость','#adbade','Еда даёт немного сил, сон восстанавливает +18/час'],clean:['Чистота','#9bc9c8','Купание смывает пыль']};
const outfitIcons={ribbon:'୨୧',lace:'❀',cord:'〰',chain:'⛓',pearl:'○',candy:'●',crystal:'◇',stars:'✧',heart:'♥',star:'★',bow:'୨୧',moon:'☾',paw:'♧',ghost:'♙',controller:'✚',cherry:'♧'};
const shellColors={smoke:{name:'Дымчатый',front:'#4c294f',back:'#2d1c3b'},milk:{name:'Молочный',front:'#e7dfce',back:'#c6b8ae'},rose:{name:'Розовый',front:'#df8fb0',back:'#a95f85'},lilac:{name:'Сиреневый',front:'#9990ce',back:'#5d507f'},cherry:{name:'Вишнёвый',front:'#7c263e',back:'#421f36'}};
let time=0,last=0,frame=0,sound=false,audio,cream=false,drag=null,targetX=-.035,targetY=-.06,renderer,scene,camera,device,screenTexture,chainGroup,accessoryGroup,buttonMeshes=[],bodyMat,backMat,buttonTimers=[0,0,0],fallback=false,uiClock=0,expressionUntil=0,expressionOverride=null;
const lcd=document.createElement('canvas');lcd.id='lcd';lcd.width=960;lcd.height=832;const ctx=lcd.getContext('2d');ctx.setTransform(4,0,0,4,0,0);
function message(t){$('status').textContent=t;}
function tone(f=700,d=.08){if(!sound)return;try{audio ||=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{sound=false;}}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Звук вкл.':'Звук выкл.';$('sound').setAttribute('aria-pressed',String(sound));tone();};
const errors={duplicate:'Награда за этот раунд уже получена.','not-owned':'Сначала добавь эту вещь в коллекцию.',unknown:'Такого действия пока нет.',asleep:'Она спит. Сначала разбуди.',full:'Пока достаточно. Можно просто побыть рядом.',cooldown:'Дай доесть: между порциями 20 секунд.',coins:'Не хватает монеток. Их дают завершённые игры.',level:'Это украшение откроется на следующем уровне.',invalid:'Не удалось прочитать сохранение.',version:'Это сохранение другой версии.', 'too-large':'Файл слишком большой: максимум 2 МБ.',egg:'Сначала вылупимся.',grave:'Это спокойная память. Забота больше не нужна.',paused:'Жизнь на паузе.',healthy:'Лекарство пока не нужно.','not-ready':'Яйцо ещё греется.','archive-full':'Архив заполнен: скачай его или удали запись.', 'not-visible':'Сначала покажи предупреждение на экране.'};
let servicePage=0;
function lifeActivity(){return {visible:document.visibilityState==='visible',drawer:!!window.TamaDrawer?.isOpen()};}
let previousActivity={visible:false,drawer:false};
function lifeTick(){const now=Date.now(),activity=lifeActivity();if(typeof L.setActivity==='function')L.setActivity(activity,now);else{L.advance(now,previousActivity);L.advance(now,activity);}previousActivity=activity;pet=L.get();}
function lifecycleText(s){const b=s.biology||{},d=s.lifecycle||{};const health=Math.round(b.health??100);const illness=d.illnessLabel||b.illness||'нет';const waste=Math.round(b.waste??0);return `${d.stageLabel||b.lifeState||'жизнь'} · здоровье ${health}/100 · недуг: ${illness} · отходы: ${waste}/3`}
function updateLifecycleUI(){const s=L.get(),d=s.lifecycle||{},b=s.biology||{};document.body.dataset.lifecycle=b.lifeState||'unknown';const warn=d.warning||'none';document.body.dataset.warning=warn;const panel=$('lifecycle-panel');if(panel){$('life-summary').textContent=lifecycleText(s);$('life-health').textContent=`Здоровье ${Math.round(b.health??100)}/100`;$('life-stage').textContent=`Этап: ${d.stageLabel||b.lifeState||'—'} · возраст: ${d.ageLabel||'—'}`;$('life-illness').textContent=`Недуг: ${d.illnessLabel||b.illness||'нет'} · отходы: ${Math.round(b.waste??0)}/3`;$('life-quality').textContent=`Качество ухода: ${d.careQuality??'—'} · счастье: ${d.happiness??'—'}`;$('life-reason').textContent=(d.attentionCauses||[]).length?'Нужна помощь: '+d.attentionCauses.join(', '):'Срочных причин нет';}}
function act(type,args={}){lifeTick();const r=L.act(type,args,Date.now());pet=r.snapshot||L.get();if(!r.ok)lifeUI.show(errors[r.code]||'Сейчас не получилось.');refresh();return r;}
function busy(){return !['idle','sleep'].includes(state.action)&&time<state.until;}
function animateAction(action,duration=4){state.action=action;state.started=time;state.until=time+duration;refresh();}
function chooseList(){return lifeUI.active()?lifeUI.list():state.menu==='food'?[...foods,{id:'back',label:'← Назад'}]:state.menu==='games'?[...gameChoices,{id:'pace',label:'Темп: '+($('snake-pace').value==='cozy'?'спокойный':'классика')},{id:'back',label:'← Назад'}]:options;}
function home(){state.menu='home';state.selected=0;state.action=pet.sleeping?'sleep':'idle';state.until=0;refresh();}
function wake(){act('wake');home();animateAction('wake',1.2);message('Йоу. Проснулась. Что будем делать?');tone(880,.12);}
function perform(id){if(game||window.TamaDrawer?.isOpen())return;if(lifeUI.active()){lifeUI.select(id);return;}if(pet.sleeping){wake();return;}if(busy()){lifeUI.show('Секундочку, она ещё занята.');return;}
if(id==='back'){home();return;}if(id==='pace'){$('snake-pace').value=$('snake-pace').value==='cozy'?'classic':'cozy';refresh();return;}
if(state.menu==='food'){const before={...pet.needs};const r=act('feed',{food:id});if(r.ok){const energyGain=Math.round(r.snapshot.needs.energy-before.energy),hungerGain=Math.round(r.snapshot.needs.hunger-before.hunger);state.food=id;home();animateAction('food');message(({cookie:'Печенька с бантом. Хрум.',soup:'Тёплый суп. Сначала остудим, потом съедим.',berry:'Ягодки — по одной, не торопясь.'})[id]+' +'+hungerGain+' сытости · +'+energyGain+' бодрости.'+rewardText(r));}return;}
if(state.menu==='games'){startGame(id);return;}
if(id==='food'||id==='game'){state.menu=id==='food'?'food':'games';state.selected=0;message(id==='food'?'Что ей приготовить?':'Во что сыграем?');refresh();return;}
if(id==='sleep'){act('sleep');state.action='sleep';state.until=0;message('Тихо. Сон возвращает силы. Любая кнопка разбудит.');refresh();return;}
const r=act(id==='bow'?'groom':'bath');if(r.ok){animateAction(id);message((id==='bow'?'Подхватили узелок. Расправляем петли и выравниваем бант.':'Пена, вода и немножко возмущения.')+rewardText(r));}}
function rewardText(r){return r.reward?.xp?' +'+r.reward.xp+' опыта.':''}
function press(which){if(window.TamaDrawer?.isOpen())return;lifeTick();buttonTimers[which]=time+.18;tone(which===1?790:530,.06);
if(game){const s=game.get();if(s.status!=='playing'){exitGame();return;}if(which===1){if(s.kind==='memory')game.input('confirm');else if(s.kind==='snake')game.input('pause');else exitGame();}else game.input(s.kind==='snake'?(which===0?'turn-left':'turn-right'):(which===0?'left':'right'));syncGameUI();return;}
if(lifeUI.specialPress(which))return;if(pet.sleeping){wake();return;}if(busy()){lifeUI.show('Секундочку, она ещё занята.');return;}
if(which!==1){if(which===2&&state.menu!=='home'){home();return;}const list=chooseList();state.selected=(state.selected+(which===0?1:-1)+list.length)%list.length;refresh();message(list[state.selected].label+' · B — выбрать');}else perform(chooseList()[state.selected].id);}
let gesture=null;
function cancelGestures(){if(gesture)clearTimeout(gesture.timer);gesture=null;drag=null;}
function beginGesture(which,source){if(window.TamaDrawer?.isOpen()||gesture)return;gesture={which,source,long:false,timer:null};const g=gesture;
const service=which===1&&!game&&state.menu==='home'&&!pet.sleeping&&!busy();const exit=which===2&&!!game;
if(service||exit)g.timer=setTimeout(()=>{if(gesture!==g||window.TamaDrawer?.isOpen())return;g.long=true;if(exit)exitGame();else lifeUI.open();},650);}
function finishGesture(source){if(!gesture||gesture.source!==source)return;const g=gesture;clearTimeout(g.timer);gesture=null;if(!g.long)press(g.which);}
for(const[id,i]of[['button-a',0],['button-b',1],['button-c',2]]){const b=$(id);b.onpointerdown=e=>{if(e.button!==0)return;beginGesture(i,id);b.setPointerCapture(e.pointerId);};b.onpointerup=()=>finishGesture(id);b.onpointercancel=cancelGestures;b.onclick=e=>{if(e.detail===0)press(i);};}
function startGame(kind){if(!pet.lifecycle.canPlay){lifeUI.show('Сначала позаботься о Семире.');return;}if(!gameChoices.some(x=>x.id===kind))return;game=TamaGames.create(kind,Math.floor(Math.random()*2147483647),{pace:$('snake-pace').value});if(kind==='snake'){targetX=0;targetY=0;}roundId=(window.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));rewarded=false;gameStart=time;state.action='game';state.until=0;message(game.get().announce);refresh();document.querySelector('.cockpit').scrollIntoView({behavior:'instant',block:'start'});}
function exitGame(){if(!game)return;const finished=game.get().status!=='playing';game=null;state.action='idle';state.menu='games';state.selected=0;clearTimeout(cKeyTimer);cKeyTimer=null;message(finished?'Сыграем ещё?':'Игра остановлена. За незавершённый раунд награды нет.');refresh();}
function direction(key){if(game){game.input(key==='confirm'&&game.get().kind==='snake'?'pause':key);syncGameUI();}}
const pad=document.createElement('div');pad.className='game-pad';document.querySelector('.control-side').append(pad);pad.append(document.querySelector('.dpad'));
let cKeyTimer=null;window.addEventListener('blur',cancelGestures);
for(const b of document.querySelectorAll('[data-direction]'))b.onclick=()=>direction(b.dataset.direction);
$('back-menu').onclick=()=>{if(game)exitGame();else home();};
document.addEventListener('keydown',e=>{if(window.TamaDrawer?.isOpen()||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;
if(e.code==='KeyB'&&e.shiftKey&&!e.repeat){e.preventDefault();cancelGestures();if(!game&&!pet.sleeping&&!busy())lifeUI.open();return;}
if((e.code==='Enter'||e.code==='Space')&&['BUTTON','SUMMARY','A'].includes(e.target.tagName))return;
if(e.code==='KeyB'||(e.code==='KeyC'&&game)){e.preventDefault();if(!e.repeat)beginGesture(e.code==='KeyB'?1:2,e.code);return;}
const dirs={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(game&&dirs[e.code]){e.preventDefault();direction(dirs[e.code]);return;}if(e.repeat)return;
if(e.code==='Escape'){cancelGestures();if(game)exitGame();else if(lifeUI.active())lifeUI.back();else home();return;}
const map={ArrowLeft:2,KeyA:0,Enter:1,Space:1,ArrowRight:0,KeyC:2};if(map[e.code]!==undefined){e.preventDefault();press(map[e.code]);}});
document.addEventListener('keyup',e=>{if(e.code==='KeyB'||e.code==='KeyC')finishGesture(e.code);});
$('reset-view').onclick=()=>{targetX=-.035;targetY=-.06;};
$('accessories').onclick=()=>TamaDrawer.open('customize');
$('theme').onclick=()=>{act('shell',{id:pet.shell==='milk'?'smoke':'milk'});applyOutfit();};
for(const b of document.querySelectorAll('[data-shell]'))b.onclick=()=>{act('shell',{id:b.dataset.shell});applyOutfit();};
function applyOutfit(){const c=shellColors[pet.shell];cream=pet.shell==='milk';if(bodyMat){bodyMat.color.set(c.front);bodyMat.opacity=cream?.98:.86;bodyMat.transmission=cream?0:.12;backMat.color.set(c.back);}wardrobe?.apply(pet.equipped);document.querySelectorAll('[data-shell]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.shell===pet.shell)));$('theme').textContent='Корпус: '+c.name.toLowerCase();$('material-label').innerHTML=c.name.toLowerCase()+' пластик<br>розовые кнопочки';}
function renderWardrobe(){const root=$('wardrobe-items');root.replaceChildren();for(const[slot,title]of[['strap','Ремешки'],['beads','Бусины'],['charm','Подвески']]){const header=document.createElement('div');header.className='slot-title';header.innerHTML='<h3>'+title+'</h3>';const off=document.createElement('button');off.textContent=pet.equipped[slot]==='none'?'Снято':'Снять';off.dataset.unequip=slot;off.disabled=pet.equipped[slot]==='none';off.onclick=()=>{act('equip',{slot,id:'none'});applyOutfit();};header.append(off);root.append(header);const grid=document.createElement('div');grid.className='wardrobe-grid';for(const item of L.catalog.filter(i=>i.slot===slot)){const card=document.createElement('div'),owned=pet.owned.includes(item.id),equipped=pet.equipped[slot]===item.id,locked=pet.level<item.level;card.className='wardrobe-item';card.dataset.item=item.id;card.dataset.equipped=equipped;card.innerHTML='<span aria-hidden="true">'+(outfitIcons[item.id]||'✧')+'</span><strong>'+item.name+'</strong><small>'+(equipped?'На тамагочи':owned?'В коллекции':locked?'С уровня '+item.level:item.cost+' монеток')+'</small>';const b=document.createElement('button');b.textContent=equipped?'Надето':owned?'Надеть':locked?'Уровень '+item.level:pet.coins<item.cost?'Нужно '+item.cost+' ✦':'Купить · '+item.cost+' ✦';b.disabled=equipped||locked||(!owned&&pet.coins<item.cost);b.dataset.wardrobe=item.id;b.onclick=()=>{if(!owned){const r=act('buy',{id:item.id});if(!r.ok)return;}$('customize-status').textContent='Надето: '+item.name;act('equip',{slot,id:item.id});applyOutfit();};card.append(b);grid.append(card);}root.append(grid);}}
function metrics(){for(const[k,[name,color,hint]]of Object.entries(needInfo)){const n=Math.round(pet.needs[k]);$('value-'+k).textContent=n+' / 100';$('bar-'+k).value=n;$('hint-'+k).textContent=n<25?'Низко · '+hint:hint;}const actionLabels={food:'Перекусывает',bath:'Купается',bow:'Поправляет бант',wake:'Проснулась'};$('mood').textContent=pet.sleeping?'Дремлет':game?'Играет':actionLabels[state.action]||'Как Семира?';$('bow-state').textContent=pet.bowNeat?'Бант на месте':'Бант растрепался';$('level-label').textContent='Уровень '+pet.level;$('coins').textContent=pet.coins+' ✦';$('stage-label').textContent=pet.level<3?'Знакомимся':pet.level<6?'Освоилась рядом':pet.level<10?'Свои маленькие привычки':'Неразлучные';$('xp-bar').value=pet.level>=20?100:pet.xp%100;$('xp-label').textContent=pet.level>=20?'Максимальный уровень · '+pet.xp+' опыта':pet.xp%100+' / 100 опыта до уровня '+(pet.level+1);$('records').innerHTML=gameChoices.map(g=>'<div class="record"><span>'+g.label+' · рекорд</span><strong>'+pet.bests[g.id]+'</strong></div>').join('');const labels={care3:'Заботливые руки', 'first-game':'Первая игра',wins3:'Три победы',level3:'Уже свои'};$('achievements').textContent=pet.achievements.length?'Значки: '+pet.achievements.map(a=>labels[a]||a).join(' · '):'Первый значок — за завершённую игру или три полезных действия ухода.';$('save-status').textContent=(pet.storage==='local'?'Сохраняется автоматически в этом браузере.':'Браузер не разрешил сохранение. Скачай файл, иначе прогресс потеряется при закрытии.')+(pet.notice?' '+pet.notice:'');document.body.dataset.action=state.action;}
let tryOn=null,tryLook=null;
function drawClothesPreview(){const canvas=$('pet-preview');if(!canvas||$('pet-wardrobe').hidden)return;const x=canvas.getContext('2d');x.clearRect(0,0,640,680);SemiiraArt.draw(x,320,345,5.4,'idle',time,reduced,{clothes:tryOn||pet.petClothes,look:tryLook!==null?tryLook:tryOn?'none':pet.petLook});}
function renderLooks(){const root=$('look-items');root.replaceChildren();const remove=document.createElement('button');remove.dataset.look='none';remove.textContent='Без наряда · исходная Семира';remove.onclick=()=>{tryLook=null;tryOn=null;act('look',{id:'none'});$('clothes-status').textContent='Вернулась исходная Семира.';drawClothesPreview();};root.append(remove);const grid=document.createElement('div');grid.className='clothes-grid look-grid';for(const item of L.lookCatalog){const card=document.createElement('div');card.className='wardrobe-item';card.dataset.lookCard=item.id;card.dataset.equipped=pet.petLook===item.id;const image=document.createElement('img');image.src=window.SEMIIRA_LOOK_SOURCES[item.id];image.alt=item.name;image.width=160;image.height=160;const title=document.createElement('strong');title.textContent=item.name;const preview=document.createElement('button');preview.dataset.lookPreview=item.id;preview.textContent='Примерить';preview.onclick=()=>{tryOn=null;tryLook=item.id;$('clothes-status').textContent='Примерка: '+item.name+'. Нажми «Надеть», чтобы сохранить.';drawClothesPreview();$('pet-preview').scrollIntoView({block:'nearest',behavior:'instant'});};const wear=document.createElement('button');wear.dataset.look=item.id;wear.textContent=pet.petLook===item.id?'Надето':'Надеть';wear.disabled=pet.petLook===item.id;wear.onclick=()=>{tryLook=null;tryOn=null;act('look',{id:item.id});$('clothes-status').textContent='На Семире: '+item.name;drawClothesPreview();};card.append(image,title,preview,wear);grid.append(card);}root.append(grid);}
function renderClothes(){tryLook=null;renderLooks();const root=$('clothes-items');root.replaceChildren();tryOn=null;for(const[slot,title]of[['neck','Шарфики и воротнички'],['cape','Накидки']]){const head=document.createElement('div');head.className='slot-title';const h=document.createElement('h3');h.textContent=title;const off=document.createElement('button');off.textContent='Снять';off.dataset.undress=slot;off.disabled=pet.petClothes[slot]==='none';off.onclick=()=>{tryOn=null;act('dress',{slot,id:'none'});$('clothes-status').textContent='Снято. Остальной наряд сохранён.';drawClothesPreview();};head.append(h,off);root.append(head);const grid=document.createElement('div');grid.className='clothes-grid';for(const item of L.clothesCatalog.filter(i=>i.slot===slot)){const owned=pet.owned.includes(item.id),equipped=pet.petClothes[slot]===item.id,locked=pet.level<item.level;const card=document.createElement('div');card.className='wardrobe-item';card.dataset.clothing=item.id;card.dataset.equipped=equipped;const name=document.createElement('strong');name.textContent=item.name;const info=document.createElement('small');info.textContent=equipped?'На Семире':owned?'В коллекции':locked?'С уровня '+item.level:item.cost+' монеток';const preview=document.createElement('button');preview.dataset.preview=item.id;preview.textContent='Примерить';preview.onclick=()=>{tryLook=null;tryOn={...pet.petClothes,[slot]:item.id};$('clothes-status').textContent='Примерка: '+item.name+'. Пока не надето и не куплено.';drawClothesPreview();$('pet-preview').scrollIntoView({block:'nearest',behavior:'instant'});};const use=document.createElement('button');use.dataset.dress=item.id;use.textContent=equipped?'Надето':owned?'Надеть':locked?'Уровень '+item.level:'Купить · '+item.cost+' ✦';use.disabled=equipped||locked||(!owned&&pet.coins<item.cost);use.onclick=()=>{if(!owned&&!act('buy',{id:item.id}).ok)return;tryOn=null;const r=act('dress',{slot,id:item.id});if(r.ok)$('clothes-status').textContent='На Семире: '+item.name+'. Сохранено.';drawClothesPreview();};card.append(name,info,preview,use);grid.append(card);}root.append(grid);}drawClothesPreview();}
let wardrobeKey='';function refresh(){lifeTick();pet=L.get();updateLifecycleUI();metrics();applyOutfit();const key=JSON.stringify([pet.shell,pet.coins,pet.level,pet.equipped,pet.owned,pet.petClothes,pet.petLook]);if(key!==wardrobeKey){renderWardrobe();renderClothes();wardrobeKey=key;}const active=!!game;document.body.dataset.playing=String(active);document.body.dataset.game=game?.get().kind||'';$('pace-control').hidden=active||state.menu!=='games';document.querySelector('.rotate-hint').textContent=game?.get().kind==='snake'?'свайп по корпусу — поворот · B — пауза':'потяни корпус · можно повертеть';$('button-a').querySelector('span').textContent='Дальше';$('button-c').querySelector('span').textContent='Назад';$('button-b').querySelector('span').textContent=pet.sleeping?'Разбудить':'Выбрать';$('action-menu').hidden=active;$('game-controls').hidden=!active;$('back-menu').hidden=!active&&state.menu==='home';$('back-menu').textContent=active?(game.get().status==='playing'?'Выйти без награды':'← К играм'):'← Назад';$('menu-location').textContent=active?gameChoices.find(g=>g.id===game.get().kind).label:state.menu==='service'?'Сервис':state.menu==='pause-confirm'?'Пауза?':state.menu==='new-life'?'Новая жизнь':state.menu==='food'?'Еда':state.menu==='games'?'Игры':'Уход';const menu=$('action-menu');menu.replaceChildren();if(!active){const list=pet.sleeping?[{id:'wake',label:'Разбудить Семиру',hint:'Сон можно прервать в любой момент'}]:chooseList();list.forEach((o,i)=>{const b=document.createElement('button');b.dataset.action=o.id;b.setAttribute('aria-pressed',String(i===state.selected));b.innerHTML='<span>'+o.label+'</span><small>'+o.hint+'</small>';b.disabled=busy();b.onclick=()=>{state.selected=i;perform(o.id);};menu.append(b);});}syncGameUI();if(renderer)resize();}
for(const[k,[name,color,hint]]of Object.entries(needInfo)){const div=document.createElement('div');div.className='need';div.style.setProperty('--need-color',color);div.innerHTML='<div class="need-head"><label for="bar-'+k+'">'+name+'</label><span id="value-'+k+'"></span></div><progress id="bar-'+k+'" max="100" value="0"></progress><small id="hint-'+k+'">'+hint+'</small>';$('needs-grid').append(div);}
const symbols=['♥','★','☾','✿','◆','♫'];let memoryKey='';function syncGameUI(){if(!game)return;const g=game.get();$('game-help').textContent=g.kind==='snake'?'Свайп по корпусу или стрелки — направление. A/C — повернуть. B, пробел или ⏸ — пауза. 8 ягод для победы.':g.kind==='stars'?'A / C или ← / → — ловить. B — выйти. Раунд длится 16 секунд.':'Стрелки / A / C — выбор, B — открыть. Карточки на экране тамагочи. 90 секунд на 6 пар.';$('game-score').textContent=g.status==='playing'?(g.paused?'Пауза · B или ▶ — продолжить':time-gameStart<1.5?'Приготовься…':g.kind==='stars'?'Поймано '+g.score+' · звезда '+g.round+' / 8':'Счёт '+g.score+' · '+Math.max(0,Math.ceil((g.timeout||90)-g.elapsed))+' сек'):((g.status==='won'?'Победа! ':'Раунд окончен. ')+'Счёт: '+g.score);$('memory-board').hidden=g.kind!=='memory';const center=document.querySelector('[data-direction=confirm]');center.disabled=!['memory','snake'].includes(g.kind)||g.status!=='playing';center.textContent=g.kind==='snake'?(g.paused?'▶':'⏸'):'●';center.setAttribute('aria-label',g.kind==='snake'?(g.paused?'Продолжить змейку':'Пауза змейки'):'Открыть карточку');if(g.kind==='memory'){const key=JSON.stringify([g.cards,g.cursor,g.status]);if(key!==memoryKey){memoryKey=key;const focused=document.activeElement?.dataset?.card;$('memory-board').replaceChildren();g.cards.forEach((c,i)=>{const b=document.createElement('button');b.dataset.card=i;b.dataset.matched=c.matched;b.setAttribute('aria-current',String(i===g.cursor));b.textContent=c.faceUp||c.matched?symbols[c.value]:'?';b.setAttribute('aria-label','Карточка '+(i+1)+': '+(c.faceUp||c.matched?symbols[c.value]:'закрыта'));b.disabled=c.matched||g.locked||g.status!=='playing';b.onclick=()=>{game.input({select:i});game.input('confirm');syncGameUI();};$('memory-board').append(b);});if(focused!==undefined)$('memory-board').querySelector('[data-card="'+focused+'"]')?.focus({preventScroll:true});}}}
$('export-save').onclick=()=>{L.advance();const url=URL.createObjectURL(new Blob([L.exportSave()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='semiira-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-message').textContent='Файл сохранения подготовлен.';};
$('import-save').onchange=async e=>{const f=e.target.files[0];pendingImport=null;$('import-confirm').hidden=true;if(!f)return;if(f.size>(L.maxImportChars||2097152)){$('save-message').textContent=errors['too-large'];e.target.value='';return;}try{pendingImport=await f.text();$('import-name').textContent='Заменить текущий прогресс файлом «'+f.name+'»?';$('import-confirm').hidden=false;}catch{$('save-message').textContent='Не удалось прочитать файл.';}e.target.value='';};
$('cancel-import').onclick=()=>{pendingImport=null;$('import-confirm').hidden=true;};$('confirm-import').onclick=()=>{if(pendingImport===null)return;const r=L.importSave(pendingImport);pendingImport=null;$('import-confirm').hidden=true;if(r.ok){game=null;pet=L.advance();state.menu='home';state.selected=0;state.action=pet.sleeping?'sleep':'idle';state.until=0;wardrobeKey='';refresh();$('save-message').textContent='Прогресс загружен.';message('Семира на месте. Продолжим.');}else $('save-message').textContent=errors[r.code]||'Некорректный файл. Текущий прогресс не изменён.';};
// Logical240x208 framebuffer at4x backing resolution.
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h);}function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fill();}
function text(s,x,y,size=9,color='#eee1ed',align='left'){ctx.fillStyle=color;ctx.font=`600 ${size}px Manrope, Arial, sans-serif`;ctx.textAlign=align;ctx.textBaseline='top';ctx.fillText(s,x,y);}
function sparkle(x,y,c='#f6d88e',s=1){rect(x-s,y-4*s,2*s,8*s,c);rect(x-4*s,y-s,8*s,2*s,c);}
function ghost(x,y,scale=1,pose='idle'){SemiiraArt.draw(ctx,x,y,scale,pose,time,reduced,{progress:Math.max(0,Math.min(1,(time-state.started)/4)),messy:!pet.bowNeat,food:state.food,clothes:pet.petClothes,look:pet.petLook});}
function drawGame(g){const titles={snake:'ЗМЕЙКА',stars:'ЗВЕЗДОПАД',memory:'ПАРОЧКИ'};text(titles[g.kind],10,7,11);text(String(g.score),229,7,11,'#f1c18e','right');
if(g.kind==='snake'){const ox=18,oy=31,cell=17;rect(ox-2,oy-2,208,174,'#45354d');rect(ox,oy,204,170,'#241d30');for(let y=0;y<10;y++)for(let x=0;x<12;x++)if((x+y)%2)rect(ox+x*cell,oy+y*cell,cell,cell,'#2b2338');if(g.food){rect(ox+g.food.x*cell+4,oy+g.food.y*cell+4,10,10,'#ef88b5');rect(ox+g.food.x*cell+8,oy+g.food.y*cell+1,3,4,'#93b89d');}g.snake.forEach((p,i)=>{rect(ox+p.x*cell+1,oy+p.y*cell+1,15,15,i?'#b9a1ce':'#f7d7e9');if(!i){rect(ox+p.x*cell+4,oy+p.y*cell+4,2,3,'#47324e');rect(ox+p.x*cell+10,oy+p.y*cell+4,2,3,'#47324e');}});}
if(g.kind==='stars'){for(let i=0;i<3;i++)rect(39+i*80,38,1,135,'#49364d');for(const d of g.drops)sparkle(40+d.lane*80,38+d.y*117,'#f6cf89',2);ghost(40+g.lane*80,161,.56,'idle');rect(19+g.lane*80,192,43,3,'#dc9dbe');text(g.round+' / 8',120,23,10,'#c5a8c2','center');}
if(g.kind==='memory'){g.cards.forEach((c,i)=>{const x=14+i%4*57,y=42+Math.floor(i/4)*51;rect(x,y,43,40,c.matched?'#46665e':c.faceUp?'#c58cad':'#563c59');text(c.faceUp||c.matched?symbols[c.value]:'?',x+21,y+9,20,c.faceUp?'#2c2037':'#e8cce0','center');if(i===g.cursor){ctx.strokeStyle='#ffd6ee';ctx.lineWidth=2;ctx.strokeRect(x-2,y-2,47,44);}});text(Math.ceil(90-g.elapsed)+' сек · '+g.moves+' ходов',120,23,10,'#c5a8c2','center');}
if(time-gameStart<1.5&&g.status==='playing'){rect(27,87,186,36,'#201827ee');text('Приготовься…',120,96,15,'#f9d4e9','center');}
if(g.paused){rect(32,86,176,48,'#23172ff2');text('ПАУЗА',120,93,18,'#f6c4df','center');text('B / ▶ — продолжить',120,116,10,'#eac6dc','center');}
if(g.status!=='playing'){rect(21,72,198,74,'#23172ff2');text(g.status==='won'?'Победа!':'Раунд завершён',120,83,17,'#f6c4df','center');text('Счёт '+g.score,120,108,12,'#f4d095','center');text('B — вернуться',120,127,10,'#d8bfd2','center');}}
function icon(id,x,y,on=false){const c=on?'#ffabd0':'#8b748c';ctx.save();ctx.translate(x,y);
if(id==='food'){rect(-5,-4,10,9,c);rect(-3,-6,6,2,c);rect(-2,-2,2,2,'#452b4b');rect(2,1,2,2,'#452b4b');}
if(id==='game'){rect(-7,-3,14,7,c);rect(-8,1,3,4,c);rect(5,1,3,4,c);rect(-4,-2,1,5,'#452b4b');rect(-6,0,5,1,'#452b4b');rect(3,-1,2,2,'#452b4b');}
if(id==='bath'){rect(-7,0,14,5,c);rect(-5,5,2,2,c);rect(3,5,2,2,c);rect(-4,-4,3,3,c);rect(2,-6,3,3,c);}
if(id==='sleep'){poly([[-2,-6],[3,-6],[0,-3],[0,2],[4,4],[7,3],[4,7],[-2,6],[-5,2],[-5,-2]],c);}
if(id==='bow'){poly([[0,0],[-7,-5],[-7,5],[0,1],[7,5],[7,-5]],c);rect(-1,-2,3,4,'#ffc3dc');}ctx.restore();}

function drawBaseScreen(){ctx.imageSmoothingEnabled=true;rect(0,0,240,208,pet.sleeping?'#191a2c':'#292334');if(game){drawGame(game.get());if(screenTexture)screenTexture.needsUpdate=true;return;}
rect(0,0,240,19,'#201a2c');text('SEMIIRA',8,4,10);text('LV '+pet.level,232,4,10,'#d6bfd7','right');let i=0;for(const[k,[name,color]]of Object.entries(needInfo)){const x=9+(i%2)*120,y=23+Math.floor(i/2)*20;text(name,x,y,8,color);rect(x+52,y+2,49,5,'#4c3a52');rect(x+52,y+2,49*pet.needs[k]/100,5,color);i++;}
for(let n=0;n<9;n++)rect((n*47+21)%236,70+(n*29)%91,1,1,'#735375');
if(state.menu!=='home'&&!pet.sleeping&&!busy()){const list=chooseList();text(state.menu==='food'?'ЧТО ПРИГОТОВИТЬ?':'ВО ЧТО СЫГРАЕМ?',120,64,11,'#efb7d8','center');list.forEach((item,i)=>{const y=85+i*20;if(i===state.selected)rect(9,y-3,222,19,'#69465f');text((i===state.selected?'› ':'  ')+item.label,17,y,12,i===state.selected?'#fff0fa':'#cbb5d0');});text('A дальше · B выбрать · C назад',120,193,9,'#d3aec9','center');if(screenTexture)screenTexture.needsUpdate=true;return;}
const bio=pet.biology||{},life=pet.lifecycle||{};if(bio.lifeState==='egg'){text('ЯЙЦО',120,72,16,'#f6d88e','center');const remain=Math.max(0,Math.ceil(((bio.hatchAt||Date.now())-Date.now())/60000));text(bio.eggReady?'ГОТОВА К ВЫЛУПЛЕНИЮ':'Греюсь… '+remain+' мин',120,96,11,'#e9cde0','center');text(bio.eggReady?'B — вылупиться':'Потребности пока заморожены',120,174,10,'#d9bfd2','center');}else if(bio.lifeState==='grave'){ghost(120,122,1.06,'sleep');text('ТИХАЯ ПАМЯТЬ',120,166,11,'#d5c3df','center');text('B — поколения',120,184,9,'#b9a8c5','center');}else{const pose=pet.sleeping?'sleep':state.action;ghost(120,122,1.06,pose==='food'&&state.food!=='cookie'?'happy':pose);}if((life.warning||'none')==='critical'&&document.visibilityState==='visible'&&!window.TamaDrawer?.isOpen()){rect(8,34,224,34,'#7a263fdd');text('НУЖНА ПОМОЩЬ',120,42,14,'#ffe1ed','center');text(life.attentionCauses?.join(' · ')||'Проверь состояние',120,59,9,'#ffd2e2','center');}
if(pet.sleeping){text('z',174,96,12,'#b8a1cb');text('Z',188,78,17,'#d2bad8');}
if(state.action==='bath'){rect(77,148,88,20,'#899caf');for(let j=0;j<12;j++){const bx=79+j*7,by=141+(j%3)*3-(reduced?0:Math.sin(time*3+j)*2);rect(bx,by,10,7,'#e3e6ec');rect(bx+2,by-3,6,4,'#f6f5fa');}for(let j=0;j<4;j++){ctx.strokeStyle='#a4bfd0';ctx.beginPath();ctx.arc(171+j%2*10,135-(time*16+j*19)%62,3,0,Math.PI*2);ctx.stroke();}}
if(state.action==='food'&&state.food==='cookie'&&pet.petLook!=='none'){rect(157,153,34,3,'#d6bbd2');rect(161,142,25,11,'#e1b17c');rect(166,140,15,3,'#f0cd9a');rect(167,146,2,2,'#84523f');rect(178,148,2,2,'#84523f');if(time-state.started>2)rect(178,140,10,8,'#292334');}
if(state.action==='food'&&state.food!=='cookie'){const x=164,y=153;if(state.food==='soup'){poly([[x-21,y-8],[x+21,y-8],[x+15,y+8],[x-14,y+8]],'#ce95b9');const eaten=reduced?1:Math.min(1,(time-state.started)/4);rect(x-20+eaten*5,y-9+eaten*7,40-eaten*10,4-eaten*2,'#e6c488');text('~',x-5,y-27,15,'#ead7e4');}else{rect(x-19,y+6,37,3,'#d6bbd2');for(let j=0;j<Math.max(0,5-Math.floor((time-state.started)*1.3));j++){ctx.fillStyle=j%2?'#9b8dcc':'#e692b1';ctx.beginPath();ctx.arc(x-12+j*6,y,4,0,Math.PI*2);ctx.fill();}}}
if(state.action==='bow'){text((time-state.started)<2?'Расправляем…':'Бант на месте',120,164,9,'#eebfdb','center');}
rect(0,175,240,33,'#211a2a');const list=chooseList();const selected=state.menu==='food'?0:state.menu==='games'?1:state.selected;for(let j=0;j<options.length;j++){const x=28+j*46;if(j===selected&&!pet.sleeping){rect(x-17,176,34,18,'#63445e');rect(x-15,193,30,1,'#e79aba');}icon(options[j].icon,x,185,j===selected&&!pet.sleeping);}text(pet.sleeping?'Нажми кнопку · разбудить':list[state.selected].label,120,196,10,'#f3d5e8','center');if(screenTexture)screenTexture.needsUpdate=true;}
function update(dt){if(window.TamaDrawer?.isOpen()&&frame%3===0)drawClothesPreview();if(frame%10===0){lifeTick();metrics();updateLifecycleUI();}
if(game&&(pet.lifecycle.warning==='critical'||!pet.lifecycle.canPlay)){game=null;state.action='idle';state.menu='home';state.selected=0;refresh();lifeUI.show('Раунд остановлен: Семире нужна забота.');}
if(game){if(time-gameStart>=1.5&&!window.TamaDrawer?.isOpen())game.tick(dt);const g=game.get();if(g.status!=='playing'&&!rewarded){rewarded=true;const r=act('reward',{id:roundId,game:g.kind,score:g.score,won:g.status==='won'});message((g.status==='won'?'Получилось! ':'Раунд окончен. ')+(r.ok?'+'+(r.reward?.coins||0)+' монеток · +'+(r.reward?.xp||0)+' опыта.':''));tone(g.status==='won'?1100:520,.15);refresh();}if(frame%6===0)syncGameUI();}else if(busy()===false&&state.action!=='idle'&&state.action!=='sleep'){state.action=pet.sleeping?'sleep':'idle';refresh();}}
function roundedShape(w,h,r){const s=new THREE.Shape(),x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s;}
function init3D(){if(!window.THREE)throw Error('Three unavailable');const T=THREE;renderer=new T.WebGLRenderer({canvas:$('device'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;scene=new T.Scene();camera=new T.PerspectiveCamera(33,1,.1,100);camera.position.set(-.32,.25,12.8);camera.lookAt(-.32,.3,0);
// Soft studio environment: long reflections make the translucent shell legible.
const env=document.createElement('canvas');env.width=1024;env.height=512;const ec=env.getContext('2d');ec.fillStyle='#30263a';ec.fillRect(0,0,1024,512);const gr=ec.createLinearGradient(0,0,0,512);gr.addColorStop(0,'#ded7ef');gr.addColorStop(.4,'#6d546f');gr.addColorStop(1,'#161022');ec.fillStyle=gr;ec.fillRect(0,0,1024,512);ec.fillStyle='#fff1f7';ec.fillRect(100,50,70,320);ec.fillStyle='#a2b6ff';ec.fillRect(670,80,50,270);ec.fillStyle='#f89dd1';ec.fillRect(900,150,65,250);const et=new T.CanvasTexture(env);et.mapping=T.EquirectangularReflectionMapping;const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromEquirectangular(et).texture;et.dispose();pm.dispose();
scene.add(new T.HemisphereLight('#ecdffa','#38263c',2));const key=new T.DirectionalLight('#ffe5f1',3.1);key.position.set(-4,5,6);scene.add(key);const rim=new T.DirectionalLight('#baaaff',2.7);rim.position.set(5,2,-2);scene.add(rim);const pink=new T.PointLight('#e857ab',10,15,2);pink.position.set(-3,-1,3);scene.add(pink);
device=new T.Group();scene.add(device);device.rotation.set(targetX,targetY,.018);
function add(geo,material,x=0,y=0,z=0,parent=device){const m=new T.Mesh(geo,material);m.position.set(x,y,z);parent.add(m);return m;}
const std=(color,rough=.45,metal=0)=>new T.MeshStandardMaterial({color,roughness:rough,metalness:metal});
function plate(w,h,r,depth,material,x,y,z){return add(new T.ExtrudeGeometry(roundedShape(w,h,r),{depth,bevelEnabled:true,bevelSize:.035,bevelThickness:.025,bevelSegments:3,curveSegments:16,steps:1}),material,x,y,z);}
const egg=new T.Shape();egg.moveTo(0,2.26);egg.bezierCurveTo(.76,2.26,1.18,1.64,1.51,.79);egg.bezierCurveTo(1.89,-.18,1.88,-1.24,1.21,-1.98);egg.bezierCurveTo(.65,-2.54,-.65,-2.54,-1.21,-1.98);egg.bezierCurveTo(-1.88,-1.24,-1.89,-.18,-1.51,.79);egg.bezierCurveTo(-1.18,1.64,-.76,2.26,0,2.26);
bodyMat=new T.MeshPhysicalMaterial({color:'#4c294f',roughness:.2,metalness:.15,transparent:true,opacity:.86,transmission:.12,thickness:.3,ior:1.47,clearcoat:1,clearcoatRoughness:.14,side:T.FrontSide});backMat=std('#2d1c3b',.34,.18);
const back=add(new T.ExtrudeGeometry(egg,{depth:.24,bevelEnabled:true,bevelSize:.17,bevelThickness:.18,bevelSegments:6,curveSegments:40}),backMat,0,0,-.41);const front=add(new T.ExtrudeGeometry(egg,{depth:.18,bevelEnabled:true,bevelSize:.17,bevelThickness:.18,bevelSegments:8,curveSegments:40}),bodyMat,0,0,-.06);
const seam=add(new T.ExtrudeGeometry(egg,{depth:.027,bevelEnabled:true,bevelSize:.183,bevelThickness:.025,bevelSegments:3,curveSegments:40}),std('#a76398',.35,.4),0,0,-.16);
// Hints of a real board under the smoke tint, tiny traces and chips around the screen.
const board=plate(2.7,3.6,.4,.04,std('#513350',.8),0,-.1,.05);for(let i=0;i<9;i++){add(new T.BoxGeometry(.025,.16+(i%3)*.12,.01),std('#c09f87',.6,.4),-1.3+i*.31,-1.13,.29);}for(const x of[-1.45,1.45]){add(new T.BoxGeometry(.11,.3,.025),std('#322338'),x,-.65,.28);for(let j=0;j<4;j++)add(new T.BoxGeometry(.16,.016,.016),std('#b894af',.4,.7),x,-.77+j*.065,.3);}
// Recessed screen bezel + LCD. Screen front is not hidden behind shell geometry.
plate(2.76,2.45,.22,.13,std('#201a29',.3,.2),0,.27,.34);plate(2.59,2.28,.16,.025,std('#827186',.35,.4),0,.27,.49);plate(2.47,2.16,.12,.015,std('#0d111c',.4),0,.27,.54);
screenTexture=new T.CanvasTexture(lcd);screenTexture.magFilter=T.LinearFilter;screenTexture.minFilter=T.LinearFilter;screenTexture.anisotropy=renderer.capabilities.getMaxAnisotropy();screenTexture.generateMipmaps=false;screenTexture.colorSpace=T.SRGBColorSpace;
add(new T.PlaneGeometry(2.39,2.07),new T.MeshBasicMaterial({map:screenTexture,toneMapped:false}),0,.27,.59);
// A narrow sheen, not a white plane obscuring the pet.
const shine=new T.Shape();shine.moveTo(-1.17,1.0);shine.lineTo(-.92,1);shine.lineTo(-1.17,.2);shine.closePath();add(new T.ShapeGeometry(shine),new T.MeshBasicMaterial({color:'#d5c1e9',transparent:true,opacity:.08,depthWrite:false}),0,.27,.598);
function label(str,w,h,size,color){const c=document.createElement('canvas');c.width=1024;c.height=Math.max(128,Math.round(1024*h/w));const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);let fontSize=c.height*.65;x.font=`600 ${fontSize}px Arial`;while(x.measureText(str).width>c.width*.91){fontSize-=2;x.font=`600 ${fontSize}px Arial`;}x.fillStyle=color;x.textAlign='center';x.textBaseline='middle';x.fillText(str,c.width/2,c.height/2);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:t,transparent:true,depthWrite:false,toneMapped:false}));}
let logo=label('SEMIIRA',1.8,.23,49,'#f3cde4');logo.position.set(0,1.8,.37);device.add(logo);let small=label('POCKET GHOST',1.3,.12,33,'#dcc2d5');small.position.set(0,1.5,.39);device.add(small);
const buttonMat=std('#ef72b0',.29,.12);for(let i=0;i<3;i++){const x=(i-1)*.78,y=-1.4+(i===1?-.16:0);const socket=add(new T.CylinderGeometry(.255,.27,.07,40),std('#1f172a',.5),x,y,.41);socket.rotation.x=Math.PI/2;const bt=add(new T.CylinderGeometry(.217,.235,.16,48),buttonMat,x,y,.53);bt.rotation.x=Math.PI/2;bt.userData.button=i;bt.userData.rest=.53;buttonMeshes.push(bt);const cap=label('ABC'[i],.19,.19,75,'#6f2e55');cap.position.set(x,y,.62);cap.userData.buttonLabel=i;device.add(cap);}
const metal=std('#c7b6d3',.21,.92);for(const[x,y]of[[-1.14,1.2],[1.14,1.2],[-.94,-1.99],[.94,-1.99]]){const screw=add(new T.CylinderGeometry(.066,.066,.025,20),metal,x,y,.37);screw.rotation.x=Math.PI/2;add(new T.BoxGeometry(.067,.015,.005),std('#44334d'),x,y,.386);add(new T.BoxGeometry(.015,.067,.005),std('#44334d'),x,y,.386);}
for(let i=0;i<5;i++)add(new T.BoxGeometry(.18,.02,.018),std('#201626'),(i-2)*.235,-2.055,.32);
// Real linked chain and tiny ribbon charm, not decorative UI graphics.
add(new T.TorusGeometry(.15,.045,10,32),metal,.92,2.03,.05);chainGroup=new T.Group();chainGroup.position.set(.93,2.09,.03);device.add(chainGroup);
for(let i=0;i<11;i++){const t=i/10,x=.1+Math.sin(t*2.7)*.77,y=.13+t*.78,z=-.04;const link=add(new T.TorusGeometry(.105,.027,8,20),metal,x,y,z,chainGroup);link.scale.y=1.22;link.rotation.y=i%2?1.14:0;link.rotation.z=-.35;}
const charm=new T.Group();charm.position.set(.48,1.0,.02);chainGroup.add(charm);const chmat=std('#dc84af',.24,.35);for(const side of[-1,1]){const sh=new T.Shape();sh.moveTo(0,0);sh.lineTo(side*.22,.14);sh.quadraticCurveTo(side*.3,.16,side*.29,0);sh.lineTo(side*.26,-.1);sh.lineTo(0,-.035);sh.closePath();add(new T.ExtrudeGeometry(sh,{depth:.045,bevelEnabled:true,bevelSize:.017,bevelThickness:.014,bevelSegments:2}),chmat,0,0,0,charm);}add(new T.SphereGeometry(.07,14,10),chmat,0,-.005,.02,charm);
// Optional physical accessory cluster: strap, pearl loop and two small charms.
// External lug: band travels out of the egg before the hanging assembly starts.
const lug=add(new T.TorusGeometry(.12,.04,10,28),metal,-1.54,1.53,.1);lug.rotation.y=.35;
const lugBridge=add(new T.BoxGeometry(.28,.11,.14),backMat,-1.38,1.53,.06);
wardrobe=makeTamaWardrobe(T,device);accessoryGroup=wardrobe.root;
const pearl=std('#eee3ed',.2,.2);for(const side of[-1,1])for(let j=0;j<3;j++)add(new T.SphereGeometry(.032,12,8),pearl,side*(1.31+j*.045),-.76-j*.11,.37);
// Soft contact shadow under floating product.
const sc=document.createElement('canvas');sc.width=sc.height=128;const sx=sc.getContext('2d'),sg=sx.createRadialGradient(64,64,4,64,64,64);sg.addColorStop(0,'#000000aa');sg.addColorStop(1,'#00000000');sx.fillStyle=sg;sx.fillRect(0,0,128,128);const sm=new T.MeshBasicMaterial({map:new T.CanvasTexture(sc),transparent:true,depthWrite:false});const shadow=add(new T.PlaneGeometry(5,2),sm,0,-2.92,-.7,scene);shadow.rotation.x=-1.15;
const ray=new T.Raycaster(),mouse=new T.Vector2();function hit(e){const r=$('device').getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);return ray.intersectObjects(buttonMeshes,false)[0];}
$('device').addEventListener('pointerdown',e=>{if(e.button!==0||window.TamaDrawer?.isOpen())return;const h=hit(e);drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false,snake:game?.get().kind==='snake',swiped:false,button:h?.object.userData.button};if(drag.button!==undefined)beginGesture(drag.button,'device');$('device').setPointerCapture(e.pointerId);});
$('device').addEventListener('pointermove',e=>{if(!drag){$('device').style.cursor=hit(e)?'pointer':'grab';return;}const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>7;if(drag.moved&&gesture){clearTimeout(gesture.timer);gesture=null;}if(drag.snake){if(!drag.swiped&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>18){const sx=e.clientX-drag.startX,sy=e.clientY-drag.startY;direction(Math.abs(sx)>Math.abs(sy)?(sx>0?'right':'left'):(sy>0?'down':'up'));drag.swiped=true;}return;}if(drag.moved){targetY=Math.max(-.9,Math.min(.9,targetY+dx*.007));targetX=Math.max(-.6,Math.min(.6,targetX+dy*.006));}drag.x=e.clientX;drag.y=e.clientY;});
$('device').addEventListener('pointerup',e=>{if(drag&&!drag.moved&&drag.button!==undefined&&hit(e)?.object.userData.button===drag.button)finishGesture('device');else cancelGestures();drag=null;});$('device').addEventListener('pointercancel',cancelGestures);$('device').addEventListener('lostpointercapture',cancelGestures);
$('device').addEventListener('webglcontextlost',e=>{e.preventDefault();showFallback();});resize();window.addEventListener('resize',resize);
window.TamaView={buttonPoint(i){const p=new T.Vector3();buttonMeshes[i].getWorldPosition(p);p.project(camera);const r=$('device').getBoundingClientRect();return{x:r.left+(p.x*.5+.5)*r.width,y:r.top+(-p.y*.5+.5)*r.height};}};
}
function resize(){if(!renderer)return;const r=$('stage').getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.position.z=Math.max(11.1,10.6/camera.aspect);camera.updateProjectionMatrix();}
function showFallback(){fallback=true;document.body.dataset.fallback='true';$('fallback').hidden=false;$('device').hidden=true;lcd.className='fallback-screen';lcd.setAttribute('aria-label','Экран Семиры');$('stage').append(lcd);}
// Simulation must not slow to a crawl when WebGL requestAnimationFrame is throttled.
let simulationLast=performance.now();
function simulate(){const now=performance.now();let elapsed=Math.min(.25,Math.max(0,(now-simulationLast)/1000));simulationLast=now;if(document.hidden)return;while(elapsed>.0001){const dt=Math.min(.05,elapsed);time+=dt;frame++;update(dt);elapsed-=dt;}drawScreen();if(fallback)lifeUI.acknowledgeCritical();}
setInterval(simulate,50);
function animate(now){requestAnimationFrame(animate);if(document.hidden||now-last<33)return;last=now;if(renderer&&!fallback){device.rotation.x+=(targetX-device.rotation.x)*.1;device.rotation.y+=(targetY-device.rotation.y)*.1;device.position.y=reduced?0:Math.sin(time*.8)*.035;chainGroup.rotation.z=reduced?0:Math.sin(time*1.5)*.04+(targetY-device.rotation.y)*.6;if(accessoryGroup)accessoryGroup.rotation.z=reduced?0:Math.max(-.035,Math.min(.035,Math.sin(time*1.35)*.012+(targetY-device.rotation.y)*.12));for(let i=0;i<3;i++){buttonMeshes[i].position.z=time<buttonTimers[i]?.47:.53;}for(const m of device.children)if(m.userData.buttonLabel!==undefined)m.position.z=time<buttonTimers[m.userData.buttonLabel]?.56:.62;renderer.render(scene,camera);lifeUI.acknowledgeCritical();}else if(fallback)lifeUI.acknowledgeCritical();}
window.Tamagotchi={getState:()=>({...JSON.parse(JSON.stringify(state)),...L.get(),game:game?.get()||null}),getAppearance:()=>({shell:pet.shell,...pet.equipped}),getEmotion:()=>SemiiraArt.currentEmotion,getAccessoryVisibility:()=>wardrobe?.visible()||[],getScreen:()=>lcd.toDataURL()};
function drawScreen(){if(!lifeUI.draw({ctx,rect,text}))drawBaseScreen();lifeUI.overlay({rect,text});if(screenTexture)screenTexture.needsUpdate=true;}
document.addEventListener('visibilitychange',()=>{cancelGestures();last=0;simulationLast=performance.now();lifeTick();metrics();});window.addEventListener('pagehide',()=>{lifeTick();L.advance(Date.now(),{visible:false,drawer:false});});
document.addEventListener('tama-drawer-open',()=>{cancelGestures();lifeTick();});document.addEventListener('tama-drawer-close',()=>lifeTick());
try{init3D();}catch(e){console.warn('3D fallback:',e.message);showFallback();}refresh();drawScreen();requestAnimationFrame(animate);
})();
